package com.jzr.nursedevice.db.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jzr.nursedevice.db.entity.PatientBeanDb;

import com.jzr.nursedevice.db.database.PatientBeanDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig patientBeanDbDaoConfig;

    private final PatientBeanDbDao patientBeanDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        patientBeanDbDaoConfig = daoConfigMap.get(PatientBeanDbDao.class).clone();
        patientBeanDbDaoConfig.initIdentityScope(type);

        patientBeanDbDao = new PatientBeanDbDao(patientBeanDbDaoConfig, this);

        registerDao(PatientBeanDb.class, patientBeanDbDao);
    }
    
    public void clear() {
        patientBeanDbDaoConfig.clearIdentityScope();
    }

    public PatientBeanDbDao getPatientBeanDbDao() {
        return patientBeanDbDao;
    }

}
