package com.jzr.nursedevice.db.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jzr.nursedevice.bean.PatientInfoBean;
import com.jzr.nursedevice.db.entity.PatientBeanDb.PatientBeanConverter;

import com.jzr.nursedevice.db.entity.PatientBeanDb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PATIENT_BEAN_DB".
*/
public class PatientBeanDbDao extends AbstractDao<PatientBeanDb, Long> {

    public static final String TABLENAME = "PATIENT_BEAN_DB";

    /**
     * Properties of entity PatientBeanDb.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PatientBean = new Property(1, String.class, "patientBean", false, "PATIENT_BEAN");
    }

    private final PatientBeanConverter patientBeanConverter = new PatientBeanConverter();

    public PatientBeanDbDao(DaoConfig config) {
        super(config);
    }
    
    public PatientBeanDbDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PATIENT_BEAN_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PATIENT_BEAN\" TEXT);"); // 1: patientBean
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PATIENT_BEAN_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PatientBeanDb entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        PatientInfoBean patientBean = entity.getPatientBean();
        if (patientBean != null) {
            stmt.bindString(2, patientBeanConverter.convertToDatabaseValue(patientBean));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PatientBeanDb entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        PatientInfoBean patientBean = entity.getPatientBean();
        if (patientBean != null) {
            stmt.bindString(2, patientBeanConverter.convertToDatabaseValue(patientBean));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PatientBeanDb readEntity(Cursor cursor, int offset) {
        PatientBeanDb entity = new PatientBeanDb( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : patientBeanConverter.convertToEntityProperty(cursor.getString(offset + 1)) // patientBean
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PatientBeanDb entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPatientBean(cursor.isNull(offset + 1) ? null : patientBeanConverter.convertToEntityProperty(cursor.getString(offset + 1)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PatientBeanDb entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PatientBeanDb entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PatientBeanDb entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
